name: habithero_flutter_ui
description: A beautiful habit tracking app with vibrant themes and animations.
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.0
  google_fonts: ^6.1.0
  flutter_animate: ^4.2.0
  confetti: ^0.8.0
  lottie: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/animations/ 