name: habithero_flutter_ui
description: A beautiful gamified habit tracker UI made in Flutter.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.0
  google_fonts: ^6.1.0
  flutter_animate: ^4.2.0
  confetti: ^0.8.0    # ✅ Updated version
  lottie: ^3.1.0


flutter:
  uses-material-design: true
  assets:
    - assets/animations/
